# this is not used, but it's here for reference
name: ape
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - matplotlib
  - pip
  - pip:
      - openai
      - anthropic
      - python-dotenv
